version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: backend
      
    container_name: example-backend
    environment:
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:${BACKEND_PORT:-8080}
      ConnectionStrings__DefaultConnection: ${DATABASE_CONNECTION_STRING:-}
      Cors__AllowedOrigins__0: ${BASE_URL:-http://localhost}
      Cors__AllowedOrigins__1: ${BASE_URL:-http://localhost}:${NGINX_LISTEN_PORT:-80}
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    networks:
      - example-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: frontend
    container_name: example-frontend
    environment:
      BASE_URL: ${BASE_URL:-http://localhost}
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      NGINX_API_PATH_SEGMENT: ${NGINX_API_PATH_SEGMENT:-api}
      ZEST_API_BASE_URL: ${BASE_URL:-http://localhost}/${NGINX_API_PATH_SEGMENT:-api}
      NGINX_LISTEN_PORT: ${NGINX_LISTEN_PORT:-80}
    ports:
      - "${NGINX_LISTEN_PORT:-80}:${NGINX_LISTEN_PORT:-80}"
    networks:
      - example-network
    volumes:
      - ./templates:/etc/nginx/templates
    depends_on:
      - backend

networks:
  example-network:
    driver: bridge

volumes:
  nginx-cache:
  nginx-logs: