name: Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore nuget/Zest.sln

    - name: Build
      run: dotnet build nuget/base/Zest.csproj --configuration Release --no-restore

    - name: Pack
      run: dotnet pack nuget/base/Zest.csproj --configuration Release --output ./artifacts

    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts/*.nupkg